### ISSUE TITLE
Improve documentation on Post Meta and other Developer documentation updates

### ISSUE THREAD

**Issue by meredevelopment** [10up/distributor#138]
Hi, The readme explains that "_Distributor does not "bring along" the referenced content or update references for arbtirary post meta_" and that "_This can be addressed on a case by case basis by extending the plugin_".

As this is so common it would be really useful to have a handful of examples for developers. Issue #81 gives a specific example of one use-case I've not found a fix to yet. Is anyone else struggling here too? 

If I, or others, provide a real-world example or two, could one of the dev team provide some how-tos?

e.g. @adamsilverstein working example of another filter usage in Issue #113 was incredibly useful!

**Comment by jeffpaul** [comment]
I'm pulling this into the 2.0.0 milestone and noting that I would like the see the following approach (yes there's :ALOT: more going on here than what the issue here asks for, but if we're going to tackle this issue then there are a couple related items also worth doing at the same time):
- [ ] document what post meta is set during push/pull and any variations for internal vs. external for an origin and remote post; ideally adding this as a new markdown file in the `Tutorials` section of the [hook docs site](https://10up.github.io/distributor/)
- [ ] Update name of [Distributor hook docs site](https://10up.github.io/distributor/) to `Distributor Developer Documentation` and move `Tutorials` section to the top before `Actions` and `Filters`
- [ ] Move the content from https://github.com/10up/distributor/#developers out of README.md and into the main page of the Distributor dev docs site (and then link from that #developers section to the dev docs site
- [ ] add to the Snippets section as per #971
- [ ] ensure we include details in the post meta info & snippets for someone to be able to handle #992 on their own
- [ ] ensure we include details in the post meta info & snippets for someone to be able to handle #741 on their own (though we'll look to build that into Distributor UX formally in v2.1)

**Comment by noraconley** [comment]
@jeffpaul I'd be happy to start working through your list.

**Comment by noraconley** [comment]
I have created a draft PR for this issue. 

Everything would benefit from review by someone with more context, but particularly:
- `docs/connect-to-an-existing-post.md` - This might benefit from more details.
- `docs/post-meta.md` - I have pulled out all post meta that I could find, but some may be mis-categorized or could benefit from more context.

**Comment by jeffpaul** [comment]
@iamdharmesh mind helping review the above as you helped with similar work elsewhere
